apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-logstash
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  type: {{ .Values.logstash.service.type }}
  ports:
    - port: {{ .Values.logstash.service.port }}
      targetPort: {{ .Values.logstash.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-grafana